
services:
  postgresql-test:
    image: "postgres:latest"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=testsuite
      - POSTGRES_PASSWORD=testsuite
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testsuite"]
      interval: 5s
      timeout: 5s
      retries: 5

  testsuite:
    build:
      context: ${PROJECT_ROOT}
      args:
        USER_TRAITS_ROOT: services/user-traits
        SQLGEN_ROOT: tools/sqlgen
      dockerfile: ${USER_TRAITS_ROOT}/testsuite/docker/testsuite/Dockerfile
    depends_on:
      postgresql-test:
        condition: service_healthy
    environment:
      - TESTSUITE_ALLOW_ROOT=1
      - PATH=/opt/yandex/testsuite/bin:/bin:/usr/bin
      - USER_TRAITS_ROOT=/testsuite/user-traits
      - PYTEST_ADDOPTS="--postgresql=postgresql://testsuite:testsuite@postgresql-test:5432/"
    working_dir: /testsuite/user-traits/testsuite
    volumes:
      - ${USER_TRAITS_ROOT}:/testsuite/user-traits
