name: ci

on:
  pull_request:
    paths:
      - 'services/ludobot/**'
      - '.github/workflows/ludobot-ci.yaml'

permissions:
  contents: read
  pull-requests: read

jobs: 
  go-bot-build:
    name: Bot Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Golang
        uses: actions/setup-go@v5
        with:
          go-version: "stable"
        
      - name: Build
        run: |
          cd services/ludobot
          make bot

      - name: Test
        run: |
          cd services/ludobot
          make test
