name: user-traits-ci

on:
  pull_request:
    paths:
      - 'services/user-traits/**'
      - '.github/workflows/user-traits-ci.yaml'

permissions:
  contents: read
  pull-requests: read

jobs: 
  build:
    name: Build service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up environment variables
        run: |
          source ./setup.sh
          echo "PROJECT_ROOT=$PROJECT_ROOT" >> $GITHUB_ENV
          echo "SQLGEN_ROOT=$SQLGEN_ROOT" >> $GITHUB_ENV
          echo "USER_TRAITS_ROOT=$USER_TRAITS_ROOT" >> $GITHUB_ENV

      - name: Set up Golang
        uses: actions/setup-go@v5
        with:
          go-version: "stable"
        
      - name: Build
        run: |
          cd services/user-traits
          make user-traits

      - name: Test
        run: |
          cd services/user-traits
          make test
      
      - name: Testsuite
        run: |
          cd services/user-traits
          make testsuite